name: jobs

on:
  push:

jobs:
  deploy-job:
    name: Deploy job
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - name: Test build output
        run: echo ${{ needs.build-job.outputs.build-output }}

  build-job:
    outputs:
      build-output: ${{ steps.buildStep.outputs.buildOut }}
    name: Build job
    runs-on: ubuntu:latest
    container:
      image: oven/bun:slim
    steps:
      - name: define output variable
        id: buildStep
        run: |
          bunver=$(bun --version)
          echo "buildOut=$bunver" >> $"GITHUB_OUTPUT"
